export const CHANGE_VIEW = "CHANGE_VIEW";
export const CHANGE_VIEW_DONT_LOG = "CHANGE_VIEW_DONT_LOG";

export const UPDATE_GET_OPPORTUNITIES_STATUS = "UPDATE_GET_OPPORTUNITIES_STATUS";
export const UPDATE_GET_OPPORTUNITIES_VALUE = "UPDATE_GET_OPPORTUNITIES_VALUE";

export const UPDATE_OPPORTUNITY_VALUE = "UPDATE_OPPORTUNITY_VALUE";

export const UPDATE_GET_ACCOUNTS_STATUS = "UPDATE_GET_ACCOUNTS_STATUS";
export const UPDATE_GET_ACCOUNTS_VALUE = "UPDATE_GET_ACCOUNTS_VALUE";

export const UPDATE_NEW_OPPORTUNITY_VALUE = "UPDATE_NEW_OPPORTUNITY_VALUE";

export const UPDATE_GET_CATEGORIES_STATUS = "UPDATE_GET_CATEGORIES_STATUS";
export const UPDATE_GET_CATEGORIES_VALUE = "UPDATE_GET_CATEGORIES_VALUE";

export const UPDATE_GET_COMPONENT_TYPES_STATUS = "UPDATE_GET_COMPONENT_TYPES_STATUS";
export const UPDATE_GET_COMPONENT_TYPES_VALUE = "UPDATE_GET_COMPONENT_TYPES_VALUE";

export const UPDATE_GET_PRODUCTS_STATUS = "UPDATE_GET_PRINCIPALS_STATUS";
export const UPDATE_GET_PRODUCTS_VALUE = "UPDATE_GET_PRODUCTS_VALUE";

export const UPDATE_GET_STAGES_STATUS = "UPDATE_GET_STAGES_STATUS";
export const UPDATE_GET_STAGES_VALUE = "UPDATE_GET_STAGES_VALUE";

export const UPDATE_GET_INDUSTRIES_STATUS = "UPDATE_GET_INDUSTRIES_STATUS";
export const UPDATE_GET_INDUSTRIES_VALUE = "UPDATE_GET_INDUSTRIES_VALUE";

export const UPDATE_COMPONENT_VALUE = "UPDATE_COMPONENT_VALUE";

export const UPDATE_ADD_OPPORTUNITY_STATUS = "UPDATE_ADD_OPPORTUNITY_STATUS";
export const UPDATE_ADD_OPPORTUNITY_VALUE = "UPDATE_ADD_OPPORTUNITY_VALUE";

export const UPDATE_COMPONENT_IN_OPPORTUNITY_VALUE = "UPDATE_COMPONENT_IN_OPPORTUNITY_VALUE";
export const UPDATE_COMPONENT_IN_OPPORTUNITY_STATUS = "UPDATE_COMPONENT_IN_OPPORTUNITY_STATUS";

export const UPDATE_ADD_COMPONENT_IN_OPPORTUNITY_VALUE = "UPDATE_ADD_COMPONENT_IN_OPPORTUNITY_VALUE";
export const UPDATE_ADD_COMPONENT_IN_OPPORTUNITY_STATUS = "UPDATE_ADD_COMPONENT_IN_OPPORTUNITY_STATUS";

export const UPDATE_NEW_ACCOUNT_STATUS = "UPDATE_NEW_ACCOUNT_STATUS";
export const UPDATE_NEW_ACCOUNT_VALUE = "UPDATE_NEW_ACCOUNT_VALUE";

export const UPDATE_SECOND_OPPORTUNITY_VALUE = "UPDATE_SECOND_OPPORTUNITY_VALUE";

export const UPDATE_MOVE_COMPONENTS_STATUS = "UPDATE_MOVE_COMPONENTS_STATUS";

export const DELETE_COMPONENT_IN_NEW_OPPORTUNITY = "DELETE_COMPONENT_IN_NEW_OPPORTUNITY";

export const UPDATE_GET_USER_INFO_VALUE = "UPDATE_GET_USER_INFO_VALUE";
export const UPDATE_GET_USER_INFO_STATUS = "UPDATE_GET_USER_INFO_STATUS";

export const STOP_THE_APP = "STOP_THE_APP";

export const UPDATE_GET_REQUIRED_USERS_VALUE = "UPDATE_GET_REQUIRED_USERS_VALUE";
export const UPDATE_GET_REQUIRED_USERS_STATUS = "UPDATE_GET_REQUIRED_USERS_STATUS";

export const APP_CRASHED = "APP_CRASHED";
export const SET_TRUE_PATH_ALREADY_RESOLVE = "SET_TRUE_PATH_ALREADY_RESOLVE";
export const UPDATE_OPPORTUNITY_STATUS = "UPDATE_OPPORTUNITY_STATUS";
